version: "3"

services:
  users:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DIRECTORY: services/users
        SCOPE: "@bakery/users"
    ports:
      - 4001:4000