version: "3"

services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:6.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  zookeeper-2:
    image: confluentinc/cp-zookeeper:6.2.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 32181:2181
  
  kafka-1:
    image: confluentinc/cp-kafka:6.2.4
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    image: confluentinc/cp-kafka:6.2.4
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - 39092:39092
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  users:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DIRECTORY: services/users
        SCOPE: "@bakery/users"
    ports:
      - 4001:4000

  auth:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DIRECTORY: services/auth
        SCOPE: "@bakery/auth"
    ports:
      - 4002:4000
    environment:
      - KAFKA_BROKERS=["kafka-1:9092","kafka-2:9092"]
      - MONGODB_URL=mongodb://root:example@auth-mongo:27017/

  auth-mongo:
    image: mongo:5.0.8
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DIRECTORY: services/scheduler
        SCOPE: "@bakery/scheduler"
    depends_on:
      - kafka-1
      - kafka-2
    ports:
      - 4003:4000
    environment:
      - KAFKA_BROKERS=["kafka-1:9092","kafka-2:9092"]