version: "3"

services:

  users:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DIRECTORY: services/users
        SCOPE: "@bakery/users"
    ports:
      - 4001:4000

  auth:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        DIRECTORY: services/auth
        SCOPE: "@bakery/auth"
    ports:
      - 4002:4000